server:
  port: 0

spring:
  application:
    name: ms-avaliador
  rabbitmq:
    host: 192.168.0.103
    port: 5672
    username: guest
    password: guest

mq:
  queues:
    avaliacao-dto: avaliacao-dto

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:ZXVyZWthLXNlcnZlcg==@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
