server:
  port: 0

spring:
  application:
    name: ms-cliente
  datasource:
    url: jdbc:h2:mem:cliente
    driver-class-name: org.h2.Driver
    username: cliente
    password: cliente
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:ZXVyZWthLXNlcnZlcg==@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log

